name: Check Debugging Challenge

on: [push, pull_request] # Runs every time they submit code

jobs:
  grade-challenge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/actions-setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Testing Tool
      run: pip install pytest

    - name: Run Test Cases
      run: pytest test_code.py
